version: "3"
services:
  db:
      image: postgres 
      restart: always  
      environment:  
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: data-products 
      volumes:  
        - ./data-products:/var/lib/postgresql/data
      ports:
        - "5438:5432"
      container_name: products